
services:
  # 1. Database (Standard Official Image)
  postgres:
    image: postgres:15-alpine
    container_name: prod-db
    environment:
      POSTGRES_USER: authnuser
      POSTGRES_PASSWORD: authnpassword
      POSTGRES_DB: authnlogix_db
    volumes:
      - prod_postgres_data:/var/lib/postgresql/data
    networks:
      - prod-network

  pgadmin:
    image: dpage/pgadmin4:7
    container_name: prod-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@authnlogix.com
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - prod-network

  # 2. Redis (Standard Official Image)
  redis:
    image: redis:7-alpine
    container_name: prod-redis
    networks:
      - prod-network

  # 3. Backend (Pulls from YOUR Docker Hub)
  authnlogix-backend:
    image: authnbroo/authnlogix-backend:v4.0  # <--- YOUR CLOUD IMAGE
    container_name: prod-backend
    expose:
      - "8080" # Main App
      - "8081" # Monitoring Side Door <--- ADD THIS
    environment:
      # In production, we talk to the service name 'postgres', not localhost
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/authnlogix_db
      SPRING_DATASOURCE_USERNAME: authnuser
      SPRING_DATASOURCE_PASSWORD: authnpassword
      SPRING_MAIL_HOST: maildev 
      SPRING_MAIL_PORT: 1025
    depends_on:
      - postgres
      - maildev
    networks:
      - prod-network

  # 4. Frontend (Pulls from YOUR Docker Hub)
  authnlogix-frontend:
    image: authnbroo/authnlogix-frontend:v4.0 # <--- YOUR CLOUD IMAGE
    container_name: prod-frontend
    ports:
      - "80:80" # The only port open to the world
    depends_on:
      - authnlogix-backend
    networks:
      - prod-network

  # 4. The Email Server (Fake SMTP)
  maildev:
    image: maildev/maildev
    container_name: prod-maildev
    ports:
      - "1080:1080" # The Web UI (Inbox)
      - "1025:1025" # The SMTP Port (Backend talks to this)
    networks:
      - prod-network

  # 5. Prometheus (The Database for Metrics)
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prod-prometheus
    ports:
      - "9090:9090" # Expose for debugging
    volumes:
      # Mount the config file we just created
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - authnlogix-backend
    networks:
      - prod-network

  # 6. Grafana (The Dashboard UI)
  grafana:
    image: grafana/grafana:10.0.0
    container_name: prod-grafana
    ports:
      - "3000:3000" # Expose UI to host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password
    depends_on:
      - prometheus
    networks:
      - prod-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: authnlogix-rabbitmq
    ports:
      - "5672:5672"   # The App Port
      - "15672:15672" # The Dashboard UI
    networks:
      - prod-network
  
  loki:
    image: grafana/loki:2.9.0
    container_name: prod-loki
    ports:
      - "3100:3100"
    volumes:
      - ./logging/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - prod-network

  # 8. Promtail (Log Collector)
  promtail:
    image: grafana/promtail:2.9.0
    container_name: prod-promtail
    # ðŸ‘‡ 1. ADD THIS COMMAND to force the config file usage
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      # ðŸ‘‡ 2. Verify this mapping matches your folder structure
      - ./logging/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks:
      - prod-network

volumes:
  prod_postgres_data:

networks:
  prod-network:
    driver: bridge