services:
  # 1. The Database
  postgres:
    image: postgres:15-alpine
    container_name: authnlogix-db
    environment:
      POSTGRES_USER: authnuser
      POSTGRES_PASSWORD: authnpassword
      POSTGRES_DB: authnlogix_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - authn-network

  # 2. Database GUI
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: authnlogix-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@authnlogix.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - authn-network

  # 3. Caching (Redis)
  redis:
    image: redis:7-alpine
    container_name: authnlogix-redis
    ports:
      - "6379:6379"
    networks:
      - authn-network

  # 3. Backend (Builds from Dockerfile)
  authnlogix-backend:
    build: ./backend
    container_name: authn-backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://authnlogix-db:5432/authnlogix_db
      SPRING_DATASOURCE_USERNAME: authnuser
      SPRING_DATASOURCE_PASSWORD: authnpassword
    depends_on:
      - postgres
    networks:
      - authn-network

  # 4. Frontend (Nginx Gateway)
  authnlogix-frontend:
    build: ./frontend
    container_name: prod-frontend
    ports:
      - "80:80" # Expose HTTP port 80 to the world
    depends_on:
      - authnlogix-backend
    networks:
      - authn-network
  
  # 4. The Email Server (Fake SMTP)
  maildev:
    image: maildev/maildev
    container_name: authnlogix-maildev
    ports:
      - "1080:1080" # The Web UI (Inbox)
      - "1025:1025" # The SMTP Port (Backend talks to this)
    networks:
      - authn-network
  
  # 5. Prometheus (The Database for Metrics)
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: prod-prometheus
    ports:
      - "9090:9090" # Expose for debugging
    volumes:
      # Mount the config file we just created
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - authnlogix-backend
    networks:
      - authn-network

  # 6. Grafana (The Dashboard UI)
  grafana:
    image: grafana/grafana:10.0.0
    container_name: prod-grafana
    ports:
      - "3000:3000" # Expose UI to host
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password
    depends_on:
      - prometheus
    networks:
      - authn-network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: authnlogix-rabbitmq
    ports:
      - "5672:5672"   # The App Port
      - "15672:15672" # The Dashboard UI
    networks:
      - authn-network

  loki:
    image: grafana/loki:2.9.0
    container_name: prod-loki
    ports:
      - "3100:3100"
    volumes:
      - ./logging/loki-config.yaml:/etc/loki/local-config.yaml
    networks:
      - authn-network

  # 8. Promtail (Log Collector)
  promtail:
    image: grafana/promtail:2.9.0
    container_name: prod-promtail
    # ðŸ‘‡ 1. ADD THIS COMMAND to force the config file usage
    command: -config.file=/etc/promtail/config.yaml
    volumes:
      # ðŸ‘‡ 2. Verify this mapping matches your folder structure
      - ./logging/promtail-config.yaml:/etc/promtail/config.yaml
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki
    networks:
      - authn-network

# Define the volumes
volumes:
  postgres_data:

# Define the network explicitly here
networks:
  authn-network:
    driver: bridge