services:
  # 1. The Database
  postgres:
    image: postgres:15-alpine
    container_name: authnlogix-db
    environment:
      POSTGRES_USER: authnuser
      POSTGRES_PASSWORD: authnpassword
      POSTGRES_DB: authnlogix_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - authn-network

  # 2. Database GUI
  pgadmin:
    image: dpage/pgadmin4:7
    container_name: authnlogix-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@authnlogix.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - authn-network

  # 3. Caching (Redis)
  redis:
    image: redis:7-alpine
    container_name: authnlogix-redis
    ports:
      - "6379:6379"
    networks:
      - authn-network

  

# Define the volumes
volumes:
  postgres_data:

# Define the network explicitly here
networks:
  authn-network:
    driver: bridge