global:
  scrape_interval: 15s # Ask "How are you?" every 15 seconds

scrape_configs:
  - job_name: "spring_boot_app"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["authnlogix-backend:8080"] # Internal Docker DNS
