spring:
  application:
    name: authnlogix-backend

  datasource:
    # Notice we use localhost here because Spring is running on your HOST machine,
    # talking to the Docker container's exposed port 5432.
    url: jdbc:postgresql://localhost:5433/authnlogix_db
    username: authnuser
    password: authnpassword
    driver-class-name: org.postgresql.Driver

    # Mail Configuration
  mail:
    host: localhost # For local dev, we use localhost because MailDev maps port 1025
    port: 1025
    username: ""
    password: ""
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

  jpa:
    hibernate:
      ddl-auto: update # In production we use 'validate', for dev 'update' is okay.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

stripe:
  secret: sk_test_51SY0juHIrDOOZus5E00iGx3wPMxrSn7ZyuNawqRFFY2yQwDBEgRRkpw3qL34Zxl72AvDoKQP83NJcjVb36pe8V3f00iIrTugb1


server:
  port: 8080
