spring:
  application:
    name: authnlogix-backend

  datasource:
    # Notice we use localhost here because Spring is running on your HOST machine,
    # talking to the Docker container's exposed port 5432.
    url: jdbc:postgresql://localhost:5432/authnlogix_db
    username: authnuser
    password: authnpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # In production we use 'validate', for dev 'update' is okay.
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080
