name: CI/CD Pipeline

# 1. Trigger: Run this only when code is pushed to 'main' branch
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: # Allows you to run it manually button click

jobs:
  build-and-push:
    runs-on: ubuntu-latest # The robot runs on a Linux Virtual Machine

    steps:
      # A. Check out your code from the repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # B. Login to Docker Hub (Uses the secrets you just set)
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # C. Build and Push Backend
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authnlogix-backend:v1.0,${{ secrets.DOCKER_USERNAME }}/authnlogix-backend:latest

      # D. Build and Push Frontend
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/authnlogix-frontend:v1.0,${{ secrets.DOCKER_USERNAME }}/authnlogix-frontend:latest